(()=>{const o=document.getElementById('captain-overlay'),p=document.getElementById('captain-panel'),scene=()=>window.pixelHarborScene;if(!o||!p)return;
const flow=[['大航海时代的咖啡馆','你也在找老板吗？先别急着去翻账本。这里每天经过的船讯，值得先记进港口见闻册。','咖啡馆里的人不只交换咖啡，也交换船期、货价和谁家的船出了事。'],['港口公告与商业消息','老板不肯随便把一张船讯贴出去，不是他爱刁难人。公告一旦公开，整座港口都会把它当成承诺。','消息写下来的那一刻，就会影响货主和承保人的安排。'],['季风与远洋航行','船东总说“只差一天”，可海上的一天从来不只是一天。','错过合适的风，船、货物和等工钱的人都会一起等待。'],['远洋船员','港口里最容易被忽略的，往往是船员的时间。他们不是站在船边的背景。','船员为一次远航预留了生活，延期会改变工资和下一份工作。'],['香料、糖与咖啡','同一艘船里，香料、糖和咖啡的命运并不一样。记录货物时，不能只写“总值”。','货物的价值、保存方式和损坏风险不同，船讯也必须写得更诚实。']];
const state=()=>{const s=HarborLife.state;s.eveLoreConversation??={index:0,done:false,seen:{}};return s.eveLoreConversation},save=()=>HarborLife.save();
const cardData={0:['大航海时代的咖啡馆','大航海时代的咖啡馆不只是喝咖啡的地方。船长、商人、承保人、账房和水手会在这里交换船期、货物、风向和海难消息，也会在这里寻找合作对象、谈生意、确认信用。\n\n这里的一张公告、一条传闻，甚至一句关于某艘船的话，都可能影响货物价格、船员工作、承保决定和整座港口的交易。'],1:['港口公告与商业消息','在通信缓慢的时代，港口公告是商人获得船期和货物消息的重要方式。公告不只是通知，也是一种公开承诺。\n\n谁先知道一艘船何时出港，谁就能先安排货物、资金和承保。消息写得不完整，损失也会传给其他人。'],2:['季风与远洋航行','大航海时代的远洋航行依赖季节、风向和洋流，错过合适的时间可能要在港口等待很久。\n\n等待会影响货物、船员工资、商人的交付和船只的运营成本。'],3:['远洋船员','远洋贸易的繁荣依靠大量船员完成。对船员来说，出航意味着工资、风险和长期离家。延期不只是日程变化，也会影响整个家庭的生活。'],4:['香料、糖与咖啡','香料、糖和咖啡连接着遥远港口之间的贸易。它们的价格、保存方式和损坏风险各不相同。\n\n一艘商船装载的是许多商人的利益，货物能否完整抵达会影响船东、货主、船员和承保人。']};
function close(){o.classList.remove('show','human-card-open');o.setAttribute('aria-hidden','true');scene().panelOpen=false}
function loreCard(i,after){const e=state();if(e.seen[i])return after();e.seen[i]=true;e.isDialoguePaused=true;e.isHumanCardOpen=true;save();const d=cardData[i],b=document.createElement('section');b.className='human-card';b.setAttribute('role','dialog');b.setAttribute('aria-modal','true');b.innerHTML=`<div class="human-card-kicker">港口见闻 · 航海知识</div><div class="human-card-mark">✦</div><h2>《${d[0]}》</h2><div class="human-card-rule"></div><div class="human-card-content">${d[1].split('\\n\\n').map(x=>`<p>${x}</p>`).join('')}</div><aside class="human-card-relation"><strong>与当前剧情的关系</strong><span>伊芙把这条见闻整理给你，让你理解老板、船东和船员争执背后的港口生活。</span></aside><button class="human-card-continue" type="button">继续交谈</button>`;o.append(b);o.classList.add('show','human-card-open');o.setAttribute('aria-hidden','false');const done=()=>{if(!b.isConnected)return;b.remove();o.classList.remove('human-card-open');e.isDialoguePaused=false;e.isHumanCardOpen=false;GameEventBus?.emit({type:'card_viewed',payload:{cardId:'eve_'+i}});save();after()};b.querySelector('button').addEventListener('click',done,{once:true});b.addEventListener('click',x=>x.stopPropagation());b.querySelector('button').focus()}
function render(){const e=state(),n=flow[e.index];if(!n){e.done=true;save();p.innerHTML='<div class="captain-linear-dialogue"><span class="captain-linear-speaker">伊芙·船讯抄写员</span><div class="captain-linear-copy">“今天的见闻先记到这里。下次港口有新船讯，我还会留一页给你。”</div><button class="captain-linear-next" type="button">▶</button></div>';p.querySelector('button').onclick=close;return}p.innerHTML=`<button class="captain-linear-close" type="button">×</button><div class="captain-linear-dialogue"><span class="captain-linear-speaker">伊芙·船讯抄写员</span><div class="captain-linear-copy">“${n[1]}”</div><button class="eve-lore-view" type="button">查看《${n[0]}》</button></div>`;p.querySelector('.captain-linear-close').onclick=close;p.querySelector('.eve-lore-view').onclick=()=>loreCard(e.index,()=>{p.innerHTML=`<div class="captain-linear-dialogue"><span class="captain-linear-speaker">伊芙·船讯抄写员</span><div class="captain-linear-copy">“${n[2]}”</div><button class="captain-linear-next" type="button">▶</button></div>`;p.querySelector('button').onclick=()=>{e.index++;save();render()}})}
function open(){const e=state();if(e.done){e.index=0;e.done=false}scene().clearDialogue();scene().panelOpen=true;o.classList.add('show');o.setAttribute('aria-hidden','false');render()}
const base=PixelHarborScene.prototype.interact;PixelHarborScene.prototype.interact=function(t,f){if(t?.kind==='npc'&&t.key==='eve'){open();return}if(t?.kind==='npc'&&t.key==='lloyd'){const x=HarborLife.state.unpostedShipNewsV3;if(x){const old=x.started;x.started=false;const r=base.call(this,t,f);x.started=old;return r}}return base.call(this,t,f)};
const css=document.createElement('style');css.textContent='.eve-lore-view{display:block;width:100%;margin:16px 0 0;padding:12px 16px;background:#714728;border:2px solid #d8a84e;color:#fff4d6;text-align:left;font:16px NotoPixelCN,sans-serif;cursor:pointer;pointer-events:auto}.eve-lore-view:hover{background:#e6bd68;color:#2d1b12}';document.head.append(css);window.EveLore={open}})();